package com.arrow37.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val startGame: String,
    val levels: String,
    val settings: String,
    val selectLevel: String,
    val language: String,
    val selectLanguage: String,
    val vibrations: String,
    val sounds: String,
    val darkMode: String,
    val nativeRefreshRate: String,
    val privacy: String,
    val termsOfService: String,
    val version: String,
    val developedBy: String,
    val close: String,
    val levelCleared: String,
    val gameOver: String,
    val nextLevel: String,
    val retry: String,
    val exit: String,
    val congratulations: String,
    val updateNow: String,
    val updateLater: String,
    val recentChanges: String
)

val EnStrings = AppStrings(
    startGame = "START GAME",
    levels = "LEVELS",
    settings = "SETTINGS",
    selectLevel = "SELECT LEVEL",
    language = "Language",
    selectLanguage = "Select Language",
    vibrations = "Vibrations",
    sounds = "Sounds",
    darkMode = "Dark mode",
    nativeRefreshRate = "Native Refresh Rate",
    privacy = "Privacy",
    termsOfService = "Terms of Service",
    version = "Version",
    developedBy = "Developed by Hamraj37",
    close = "Close",
    levelCleared = "Level Cleared!",
    gameOver = "Game Over",
    nextLevel = "NEXT LEVEL",
    retry = "RETRY",
    exit = "EXIT",
    congratulations = "Congratulations!\nYou've mastered this puzzle.",
    updateNow = "Update Now",
    updateLater = "Update Later",
    recentChanges = "Recent Changes:"
)

val EsStrings = AppStrings(
    startGame = "INICIAR JUEGO",
    levels = "NIVELES",
    settings = "AJUSTES",
    selectLevel = "SELECCIONAR NIVEL",
    language = "Idioma",
    selectLanguage = "Seleccionar idioma",
    vibrations = "Vibraciones",
    sounds = "Sonidos",
    darkMode = "Modo oscuro",
    nativeRefreshRate = "Frecuencia de actualización nativa",
    privacy = "Privacidad",
    termsOfService = "Términos de servicio",
    version = "Versión",
    developedBy = "Desarrollado por Hamraj37",
    close = "Cerrar",
    levelCleared = "¡Nivel superado!",
    gameOver = "Fin del juego",
    nextLevel = "SIGUIENTE NIVEL",
    retry = "REINTENTAR",
    exit = "SALIR",
    congratulations = "¡Felicidades!\nHas dominado este puzzle.",
    updateNow = "Actualizar ahora",
    updateLater = "Más tarde",
    recentChanges = "Cambios recientes:"
)

val FrStrings = AppStrings(
    startGame = "DÉMARRER LE JEU",
    levels = "NIVEAUX",
    settings = "PARAMÈTRES",
    selectLevel = "CHOISIR UN NIVEAU",
    language = "Langue",
    selectLanguage = "Choisir la langue",
    vibrations = "Vibrations",
    sounds = "Sons",
    darkMode = "Mode sombre",
    nativeRefreshRate = "Taux de rafraîchissement natif",
    privacy = "Confidentialité",
    termsOfService = "Conditions d'utilisation",
    version = "Version",
    developedBy = "Développé par Hamraj37",
    close = "Fermer",
    levelCleared = "Niveau terminé !",
    gameOver = "Jeu terminé",
    nextLevel = "NIVEAU SUIVANT",
    retry = "RÉESSAYER",
    exit = "QUITTER",
    congratulations = "Félicitations !\nVous avez maîtrisé ce puzzle.",
    updateNow = "Mettre à jour maintenant",
    updateLater = "Plus tard",
    recentChanges = "Changements récents :"
)

val DeStrings = AppStrings(
    startGame = "SPIEL STARTEN",
    levels = "LEVEL",
    settings = "EINSTELLUNGEN",
    selectLevel = "LEVEL WÄHLEN",
    language = "Sprache",
    selectLanguage = "Sprache wählen",
    vibrations = "Vibrationen",
    sounds = "Töne",
    darkMode = "Dunkelmodus",
    nativeRefreshRate = "Native Bildwiederholfrequenz",
    privacy = "Datenschutz",
    termsOfService = "Nutzungsbedingungen",
    version = "Version",
    developedBy = "Entwickelt von Hamraj37",
    close = "Schließen",
    levelCleared = "Level geschafft!",
    gameOver = "Spiel vorbei",
    nextLevel = "NÄCHSTES LEVEL",
    retry = "WIEDERHOLEN",
    exit = "BEENDEN",
    congratulations = "Herzlichen Glückwunsch!\nDu hast dieses Rätsel gelöst.",
    updateNow = "Jetzt aktualisieren",
    updateLater = "Später",
    recentChanges = "Letzte Änderungen:"
)

val JaStrings = AppStrings(
    startGame = "ゲーム開始",
    levels = "レベル",
    settings = "設定",
    selectLevel = "レベル選択",
    language = "言語",
    selectLanguage = "言語を選択",
    vibrations = "バイブレーション",
    sounds = "サウンド",
    darkMode = "ダークモード",
    nativeRefreshRate = "ネイティブリフレッシュレート",
    privacy = "プライバシー",
    termsOfService = "利用規約",
    version = "バージョン",
    developedBy = "Hamraj37による開発",
    close = "閉じる",
    levelCleared = "レベルクリア！",
    gameOver = "ゲームオーバー",
    nextLevel = "次のレベルへ",
    retry = "リトライ",
    exit = "終了",
    congratulations = "おめでとうございます！\nこのパズルをマスターしました。",
    updateNow = "今すぐ更新",
    updateLater = "後で",
    recentChanges = "最近の変更点："
)

val LocalAppStrings = staticCompositionLocalOf { EnStrings }
