name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease
      env:
        SIGNING_KEY_STORE_BASE64: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        UNITY_GAME_ID: ${{ secrets.UNITY_GAME_ID }}
        UNITY_REWARDED_ID: ${{ secrets.UNITY_REWARDED_ID }}
        UNITY_BANNER_ID: ${{ secrets.UNITY_BANNER_ID }}
        UNITY_TEST_MODE: false

    - name: Build Release Bundle
      run: ./gradlew bundleRelease
      env:
        SIGNING_KEY_STORE_BASE64: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        UNITY_GAME_ID: ${{ secrets.UNITY_GAME_ID }}
        UNITY_REWARDED_ID: ${{ secrets.UNITY_REWARDED_ID }}
        UNITY_BANNER_ID: ${{ secrets.UNITY_BANNER_ID }}
        UNITY_TEST_MODE: false

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app/build/outputs/apk/release/*.apk

    - name: Upload Bundle
      uses: actions/upload-artifact@v4
      with:
        name: release-bundle
        path: app/build/outputs/bundle/release/*.aab

    - name: Get Release Info
      id: release_info
      run: |
        VERSION_NAME=$(grep "versionName =" app/build.gradle.kts | awk -F '"' '{print $2}')
        COMMIT_MSG=$(git log -1 --pretty=%B)
        echo "version=$VERSION_NAME" >> $GITHUB_OUTPUT
        echo "commit_msg<<EOF" >> $GITHUB_OUTPUT
        echo "$COMMIT_MSG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.release_info.outputs.version }}
        name: Release v${{ steps.release_info.outputs.version }}
        body: |
          ${{ steps.release_info.outputs.commit_msg }}
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          app/build/outputs/apk/release/*.apk
          app/build/outputs/bundle/release/*.aab
